<a href="https://colab.research.google.com/github/Ahiraf/Data_Science_Basics/blob/main/12_One_Hot_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **In Machine Learning, encoding means converting categorical (text) data into numerical form so that a machine learning model can understand it.**

### **Most ML algorithms work with numbers, not text.**
### **So we transform values like "Male", "Female", "Urban", "Rural" into numbers. This transformation process is called encoding.**

## **Nominal data (no order) → One-Hot Encoding**<br>**Ordinal data (has order) → Label / Ordinal Encoding**

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('/content/loan.csv')
dataset.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [4]:
dataset.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

### **Gender, Married, Education, Property_Area columns are nominal categorical variables, so we use One-Hot Encoding.**

### **Among these columns Gender and Married columns have NaN values.**

In [7]:
dataset.fillna({"Gender": dataset["Gender"].mode()[0]}, inplace = True)
dataset.fillna({"Married": dataset["Married"].mode()[0]}, inplace = True)

In [8]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

# **# One-Hot Encoding can be performed in two ways: using Pandas or using Scikit-learn.**

# **Using Pandas:**

In [13]:
en_data = dataset[["Gender", "Married"]]

pd.get_dummies(en_data)

     Gender_Female  Gender_Male  Married_No  Married_Yes
0            False         True        True        False
1            False         True       False         True
2            False         True       False         True
3            False         True       False         True
4            False         True        True        False
..             ...          ...         ...          ...
609           True        False        True        False
610          False         True       False         True
611          False         True       False         True
612          False         True       False         True
613           True        False        True        False

[614 rows x 4 columns]

Here True = 1 and False = 0 or boolean types data.

In [14]:
pd.get_dummies(en_data).info()
# After encoding, the "Gender" column will be converted into two columns: Gender_Female and Gender_Male.
# Similarly, the "Married" column will be converted into Married_No and Married_Yes.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  614 non-null    bool
 1   Gender_Male    614 non-null    bool
 2   Married_No     614 non-null    bool
 3   Married_Yes    614 non-null    bool
dtypes: bool(4)
memory usage: 2.5 KB

# **For Example:**
| Gender | Gender_Female | Gender_Male |
| ------ | ------------- | ----------- |
| Female | 1             | 0           |
| Male   | 0             | 1           |

# **Using Scikit-learn:**

In [10]:
!pip install sklearn.preprocessing

Collecting sklearn.preprocessing
  Downloading sklearn_preprocessing-0.1.0-py3-none-any.whl.metadata (70 bytes)
Downloading sklearn_preprocessing-0.1.0-py3-none-any.whl (10 kB)
Installing collected packages: sklearn.preprocessing
Successfully installed sklearn.preprocessing-0.1.0

In [12]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
ohe = OneHotEncoder()
ohe.fit_transform(en_data) # fit_transform() converts categorical data into numerical form using a Scikit-learn encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1228 stored elements and shape (614, 4)>

### **Small concept clarification (important)**
 **fit_transform() actually does two steps:**

###**1️⃣ fit()**
**Learns the categories from the data.<br>
Example: Male, Female**

###**2️⃣ transform()**
**Converts them into numbers or encoded vectors**


## ---

**So, fit_transform() = fit() + transform()**

**Sparse matrix: a matrix in which most elements are 0 and only a few are non-zero.**

**This happens often after One-Hot Encoding, which is why libraries like Scikit-learn return sparse matrices to save memory.**

In [21]:
# Converting Sparse Matrix to Array

arr = ohe.fit_transform(en_data).toarray()
arr

array([[0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       ...,
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [20]:
#Converting array to DataFrame

pd.DataFrame(arr, columns = ["Gender_Female", "Gender_Male", "Married_No", "Married_Yes"])

     Gender_Female  Gender_Male  Married_No  Married_Yes
0              0.0          1.0         1.0          0.0
1              0.0          1.0         0.0          1.0
2              0.0          1.0         0.0          1.0
3              0.0          1.0         0.0          1.0
4              0.0          1.0         1.0          0.0
..             ...          ...         ...          ...
609            1.0          0.0         1.0          0.0
610            0.0          1.0         0.0          1.0
611            0.0          1.0         0.0          1.0
612            0.0          1.0         0.0          1.0
613            1.0          0.0         1.0          0.0

[614 rows x 4 columns]

# **One-Hot Encoding creates multiple new columns, so we drop one column to avoid redundancy.**

**If we already know Gender_Female, we automatically know Gender_Male.**
**Example:**

### **Female = 1 → Male = 0** <br> **Female = 0 → Male = 1**

**So one column is redundant.**

In [22]:
ohe = OneHotEncoder(drop = "first") # pd.get_dummies(dataset, drop_first=True)
ohe.fit_transform(en_data)

arr = ohe.fit_transform(en_data).toarray()
arr

array([[1., 0.],
       [1., 1.],
       [1., 1.],
       ...,
       [1., 1.],
       [1., 1.],
       [0., 0.]])

In [24]:
pd.DataFrame(arr, columns = ["Gender_Male", "Married_Yes"])

     Gender_Male  Married_Yes
0            1.0          0.0
1            1.0          1.0
2            1.0          1.0
3            1.0          1.0
4            1.0          0.0
..           ...          ...
609          0.0          0.0
610          1.0          1.0
611          1.0          1.0
612          1.0          1.0
613          0.0          0.0

[614 rows x 2 columns]

##**After using drop='first', if Gender_Male = 1 then the gender is Male, and if Gender_Male = 0 then the gender is Female.**