<a href="https://colab.research.google.com/github/Ahiraf/Data_Science_Basics/blob/main/14_Ordinal_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [80]:
df = pd.DataFrame({"Size": ["s", "m", "l", "xl", "s", "m", "l", "s", "s", "l", "xl", "m"]})
df.head(3)

  Size
0    s
1    m
2    l

In [81]:
ord_data = [["s", "m", "l", "xl"]]

In [82]:
from sklearn.preprocessing import OrdinalEncoder

In [83]:
oe = OrdinalEncoder(categories=ord_data)
# If categories='auto', the encoder assigns numbers based on the alphabetical order of categories.
# Here we provide ord_data to define the desired order of categories manually.

In [84]:
oe.fit(df[["Size"]])

OrdinalEncoder(categories=[['s', 'm', 'l', 'xl']])

In [85]:
df["Size_en"] = oe.transform(df[["Size"]])
df

   Size  Size_en
0     s      0.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     s      0.0
5     m      1.0
6     l      2.0
7     s      0.0
8     s      0.0
9     l      2.0
10   xl      3.0
11    m      1.0

# **Encoding using Map Function**

In [86]:
ord_data1 = {"s": 0, "m": 1, "l": 2, "xl": 3}
# Custom mapping for ordinal categories; any numerical values can be assigned using map(),
# e.g., 5, 6, 7, 8 instead of 0, 1, 2, 3.

In [89]:
df["Size_en1"] = df["Size"].map(ord_data1)
df

   Size  Size_en  Size_en1
0     s      0.0         0
1     m      1.0         1
2     l      2.0         2
3    xl      3.0         3
4     s      0.0         0
5     m      1.0         1
6     l      2.0         2
7     s      0.0         0
8     s      0.0         0
9     l      2.0         2
10   xl      3.0         3
11    m      1.0         1

In [64]:
dataset = pd.read_csv('/content/loan.csv')
dataset.head(3)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

**Here Property_Area is Ordinal categorical data type as Urban > Semiurban > Rural**

In [90]:
dataset["Property_Area"].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [91]:
en_data_ord = [['Rural', 'Semiurban', 'Urban']]

In [93]:
oen = OrdinalEncoder(categories= en_data_ord)
dataset["Property_Area"] = oen.fit_transform(dataset[["Property_Area"]])
dataset.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,2.0,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,0.0,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,2.0,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,2.0,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,2.0,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,2.0,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,2.0,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,1.0,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,2.0,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,1.0,N